### ISSUE TITLE
F8: To-do Widget

### ISSUE THREAD

**Issue by EwhanHan** [WITS-Team-1/client#12]
![image](https://user-images.githubusercontent.com/40779221/151029776-1e9cdee7-9d52-4f79-b7be-24a8f991a3d2.png)
![image](https://user-images.githubusercontent.com/40779221/151029913-25494064-b291-4651-9b1f-f25de066679b.png)

Requirements:

- [ ] 1. pressing 'x' should hide this widget
- [ ] 2. pressing 'Add new task' should bring up an empty to-do item
- [ ] To-do item should contain an input area that accepts strings, and has a checkbox (please refer to image)
- [ ] 3. pressing the checkbox, should mark 'X' on the to-do list item
- [ ] please ensure the size/font/colour follows the Figma design specification

There are many youtube videos on React To-Do Lists/components

Question for designers:
- Do any of these to-do items disappear/delete?
